In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Convolution2D
from keras.layers.convolutional import MaxPooling2D
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from keras import backend as K

Using TensorFlow backend.


In [2]:
from sklearn.model_selection import train_test_split

train = pd.read_csv("/Users/j0s023m/Downloads/model_data_for_Sundi.csv").values

X=train[:,:-1]
y=train[:,-1]

X_train_df, X_test, y_train_df, y_test = train_test_split(X, y, random_state=42, stratify=y,  test_size = 0.2)


In [74]:
#X_train_df[:, 1:].reshape(X_train_df.shape[0],1,28, 28).astype( 'float32' )
#out = X_train_df.reshape((-1,1,119,1))


In [3]:
X_train_df = X_train_df.reshape((-1,1,119,1)).astype( 'float32' )

X_test = X_test.reshape((-1,1,119,1)).astype( 'float32' )



In [4]:
from keras.utils import to_categorical

y_train_df_rs = to_categorical(y_train_df)
y_test_rs = to_categorical(y_test)


In [22]:
from keras.optimizers import Adam

model = Sequential()
#K.set_image_dim_ordering('th')
model.add(Convolution2D(30, 1, 1, border_mode= 'valid' , input_shape=(1, 119,1),activation= 'relu' ))
model.add(MaxPooling2D(pool_size=(1, 1)))
model.add(Convolution2D(15, 1, 1, activation= 'relu' ))
model.add(MaxPooling2D(pool_size=(1, 1)))
model.add(Dropout(0.1))
model.add(Flatten())
model.add(Dense(64, activation= 'relu' ))
model.add(Dense(32, activation= 'relu' ))
model.add(Dense(3, activation= 'softmax' ))
  # Compile model
model.compile(loss= 'categorical_crossentropy' , optimizer=Adam(lr=0.005) , metrics=[ 'accuracy' ])

/Users/j0s023m/Desktop/handson-deep_q_learning_stock_trading/y37/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(30, (1, 1), input_shape=(1, 119, 1..., activation="relu", padding="valid")`
  """
/Users/j0s023m/Desktop/handson-deep_q_learning_stock_trading/y37/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(15, (1, 1), activation="relu")`
  import sys


In [23]:
model.fit(X_train_df, y_train_df_rs,
          epochs=32,
          batch_size= 160,
          verbose=1)


Epoch 1/32
1299/1299 [==============================] - 3s 2ms/step - loss: 1.3122 - acc: 0.4488
Epoch 2/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.9155 - acc: 0.5435
Epoch 3/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.8729 - acc: 0.5766
Epoch 4/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.8637 - acc: 0.5812
Epoch 5/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.8425 - acc: 0.5828
Epoch 6/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.8243 - acc: 0.6135
Epoch 7/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.8048 - acc: 0.6228
Epoch 8/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.8024 - acc: 0.6174
Epoch 9/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.8201 - acc: 0.5912
Epoch 10/32
1299/1299 [==============================] - 1s 1ms/step - loss: 0.7832 - acc: 0.6451
Epoch 11/32
1299/1299 [======

In [24]:
score = model.evaluate(X_test, y_test_rs, batch_size=128)
score

325/325 [==============================] - 0s 1ms/step


[0.8163301583436819, 0.6523076965258672]

In [25]:
predictions = model.predict_classes(X_test, batch_size=128)


In [26]:
#predictions
#y_test
from sklearn.metrics import confusion_matrix
cnm = confusion_matrix(predictions, y_test)
print(cnm)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(predictions, y_test)
accuracy_count = accuracy_score(predictions, predictions, normalize = False) ###3 number of correctly classified 
print("--------- accuracy ------------")
print(accuracy , accuracy_count)

[[102  29   8]
 [ 47 106  22]
 [  3   4   4]]
--------- accuracy ------------
0.6523076923076923 325


In [27]:
score

[0.8163301583436819, 0.6523076965258672]

In [38]:
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 1, 119, 30)        60        
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 1, 119, 30)        0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 1, 119, 15)        465       
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 1, 119, 15)        0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 1, 119, 15)        0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 1785)              0         
_________________________________________________________________
dense_15 (Dense)             (None, 64)                114304    
__________

In [37]:
# import shap

# # we use the first 100 training examples as our background dataset to integrate over
# K.backend.get_session().run(tf.global_variables_initializer())


# explainer = shap.DeepExplainer(model, X_train_df)

# # explain the first 10 predictions
# # explaining each prediction requires 2 * background dataset size runs
# shap_values = explainer.shap_values(X_test[:10])

AttributeError: 'function' object has no attribute 'get_session'